--- #YAML:1.0
name:               Finance-YahooQuote
version:            0.23
abstract:           Gets stock quotes from Yahoo! Finance
author:
    - Dirk Eddelbuettel (edd@debian.org)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    HTML::Parser:      2.2
    HTTP::Request:     1.23
    LWP::UserAgent:    1.62
    Text::ParseWords:  3.1
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
